name: Distribute Android Builds to Firebase

on:
  push:
    branches:
      - master

jobs:
  distribute:
    runs-on: ubuntu-latest
    outputs:
      source-branch: master
      gha_link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        id: change-java-version
        with:
          distribution: jetbrains
          java-version: 21

      - name: Set Google account credentials
        shell: bash
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > firebase_credentials.json
          echo $(readlink -f firebase_credentials.json)
          echo GOOGLE_APPLICATION_CREDENTIALS=$(echo $(readlink -f firebase_credentials.json)) >> $GITHUB_ENV

      - name: Setup Version Code
        id: setup_version_code
        shell: bash
        run: |
          BUILD_NUMBER_OFFSET=300000
          APP_VERSION_CODE=$((${{ github.run_number }} + $BUILD_NUMBER_OFFSET))
          sed -i "s/^ext.versionCode =.*/ext.versionCode = $APP_VERSION_CODE/" project-config.gradle.kts
          echo "App version code set to $APP_VERSION_CODE"
          echo "app_version_code=$APP_VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Set release notes
        id: set-release-notes
        shell: bash
        run: |

          branch="${{ needs.setup.outputs.source-branch }}"
          gha_link="${{ needs.setup.outputs.gha_link }}"

          notes=$(git --no-pager log --pretty=tformat:'%s <%an>%n' -n 20 --no-merges)

          NL=$'\n\n'
          header="**Branch**: ${branch}${NL}**GHA:** ${gha_link}${NL}**Commits:**${NL}"

          echo "${header}${notes}" > release_notes_file

          cat release_notes_file

      - name: Build and distribute to Firebase
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

        run: |
          KEYSTORE="androidApp/release.jks"

          ./gradlew :androidApp:clean
          ./gradlew assembleDebug appDistributionUploadDebug --releaseNotesFile=release_notes_file
          ./gradlew assembleRelease appDistributionUploadRelease --releaseNotesFile=release_notes_file
