name: Distribute iOS Builds to Firebase

#on:
#  pull_request:
#    branches:
#      - master

jobs:
  distribute:
    runs-on: macos-latest
    outputs:
      source-branch: master
      gha_link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4' # Adjust to your Xcode version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set Google account credentials
        shell: bash
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > firebase_credentials.json
          echo $(readlink -f firebase_credentials.json)
          echo GOOGLE_APPLICATION_CREDENTIALS=$(echo $(readlink -f firebase_credentials.json)) >> $GITHUB_ENV

      - name: Set release notes
        id: set-release-notes
        shell: bash
        run: |

          branch="${{ needs.setup.outputs.source-branch }}"
          gha_link="${{ needs.setup.outputs.gha_link }}"

          notes=$(git --no-pager log --pretty=tformat:'%s <%an>%n' -n 20 --no-merges)

          NL=$'\n\n'
          header="**Branch**: ${branch}${NL}**GHA:** ${gha_link}${NL}**Commits:**${NL}"

          echo "${header}${notes}" > release_notes_file

          cat release_notes_file


      - name: Build and Archive iOS App
        working-directory: iosApp
        run: |
          xcodebuild -project iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Debug \
            -archivePath ./build/iosApp.xcarchive \
            archive

      - name: Export IPA
        working-directory: iosApp
        run: |
          xcodebuild -exportArchive \
            -archivePath ./build/iosApp.xcarchive \
            -exportPath ./build \
            -exportOptionsPlist exportOptions.plist

      - name: Distribute iOS IPA to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        working-directory: iosApp
        run: |
          firebase appdistribution:distribute build/iosApp.ipa \
            --app "YOUR_IOS_APP_ID" \
            --release-notes "iOS Debug - $(date +%Y-%m-%d)" 

      - name: Upload iOS IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: iosApp/build/*.ipa
