name: iOS

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build and Compile
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint (for static analysis like detekt)
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint

      - name: Build on Simulator
        working-directory: iosApp
        run: |
          xcodebuild clean build \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""